version: 2.1
orbs:
  heroku: circleci/heroku@1.2.6
  windows: circleci/windows@2.4.1
jobs:
  build:
    working_directory: ~/product-service-api/Source/AllSopFoodService
    description: Build application with Release configuration
    executor:
      name: windows/default
    steps:
      - checkout:
          path: ~/product-service-api
      - restore_cache:
          keys:
            - dotnet-packages-v1-{{ checksum "AllSopFoodService.csproj" }}
      - run:
          name: "Install project dependencies"
          command: dotnet.exe restore
      - run:
          name: "Build Application according to some given configuration"
          command: dotnet.exe build --configuration Release
workflows:
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git